### ISSUE TITLE
Add button crash

### ISSUE THREAD

**Issue by ZackerySpytz** [CMPUT301W17T06/MoodBook#36]
Sometimes selecting the "Add" button under follows results in this crash:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.cmput301.cmput301w127t06.moodbook, PID: 3052
                  java.util.ConcurrentModificationException
                      at java.util.ArrayList$Itr.next(ArrayList.java:831)
                      at com.cmput301.cmput301w127t06.moodbook.Follows.removeFromFollowRequests(Follows.java:212)
                      at com.cmput301.cmput301w127t06.moodbook.FollowListAdapter$2.onClick(FollowListAdapter.java:202)
                      at android.view.View.performClick(View.java:5637)
                      at android.view.View$PerformClick.run(View.java:22429)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6119)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by ZackerySpytz** [comment]
This is caused because the Follows class attempts to remove objects from ArrayLists while iterating.
